import {
	challengeOneDefinition,
	challengeTwoDefinition,
	challengeThreeDefinition,
	challengeFourDefinition,
	challengeFiveDefinition,
	challengeSixDefinition,
	challengeSevenDefinition,
	challengeEightDefinition,
	challengeNineDefinition,
	challengeTenDefinition,
	challengeElevenDefinition,
	challengeTwelveDefinition,
	challengeThirteenDefinition,
} from './definitions';
import {
	challengeOneCode,
	challengeTwoCode,
	challengeThreeCode,
	challengeFourCode,
	challengeFiveCode,
	challengeSixCode,
	challengeSevenCode,
	challengeEightCode,
	challengeNineCode,
	challengeTenCode,
	challengeElevenCode,
	challengeTwelveCode,
	challengeThirteenCode,
} from './code';

const challenges = [
	{
		title: '100 Kids Vs 100 Adults For $500,000',
		videoID: '0CTp1a-aCUM',
		challengeDefinition: challengeOneDefinition,
		challengeCode: challengeOneCode,
		challengeAnswer: '',
	},
	{
		title: 'Last To Take Hand Off Jet, Keeps It!',
		videoID: 'kX3nB4PpJko',
		challengeDefinition: challengeTwoDefinition,
		challengeCode: challengeTwoCode,
		challengeAnswer: '',
	},
	{
		title: '$1 vs $1,000,000 Hotel Room!',
		videoID: 'iogcY_4xGjo',
		challengeDefinition: challengeThreeDefinition,
		challengeCode: challengeThreeCode,
		challengeAnswer: '',
	},
	{
		title: 'Survive 100 Days In Circle, Win $500,000',
		videoID: 'gHzuabZUd6c',
		challengeDefinition: challengeFourDefinition,
		challengeCode: challengeFourCode,
		challengeAnswer: '',
	},
	{
		title: 'I Hunted 100 People!',
		videoID: '65fN_OUawjk',
		challengeDefinition: challengeFiveDefinition,
		challengeCode: challengeFiveCode,
		challengeAnswer: '',
	},
	{
		title: 'Hydraulic Press Vs Lamborghini',
		videoID: 'h5NvTTOlOtI',
		challengeDefinition: challengeSixDefinition,
		challengeCode: challengeSixCode,
		challengeAnswer: '',
	},
	{
		title: 'I Survived A Plane Crash',
		videoID: 'jdMNoQE3mIQ',
		challengeDefinition: challengeSevenDefinition,
		challengeCode: challengeSevenCode,
		challengeAnswer: '',
	},
	{
		title: 'I Gave My 100,000,000th Subscriber An Island',
		videoID: '2isYuQZMbdU',
		challengeDefinition: challengeEightDefinition,
		challengeCode: challengeEightCode,
		challengeAnswer: '',
	},
	{
		title: '100 Girls Vs 100 Boys For $500,000',
		videoID: 'tVWWp1PqDus',
		challengeDefinition: challengeNineDefinition,
		challengeCode: challengeNineCode,
		challengeAnswer: '',
	},
	{
		title: 'I Didn’t Eat Food For 30 Days',
		videoID: 'vaIgyRoUkQI',
		challengeDefinition: challengeTenDefinition,
		challengeCode: challengeTenCode,
		challengeAnswer: '',
	},
	{
		title: "I Built Willy Wonka's Chocolate Factory!",
		videoID: 'Hwybp38GnZw',
		challengeDefinition: challengeElevenDefinition,
		challengeCode: challengeElevenCode,
		challengeAnswer: '',
	},
	{
		title: '$10,000 Every Day You Survive Prison',
		videoID: 'hD1YtmKXNb4',
		challengeDefinition: challengeTwelveDefinition,
		challengeCode: challengeTwelveCode,
		challengeAnswer: '',
	},
	{
		title: 'Would You Swim With Sharks For $100,000?',
		videoID: 'LnlKwzc_TNA',
		challengeDefinition: challengeThirteenDefinition,
		challengeCode: challengeThirteenCode,
		challengeAnswer: '',
	},
];

export default challenges;
